version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=workflowdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma
    restart: always
    ports:
      - '8001:8000' # Exposes ChromaDB on port 8001 to avoid conflict with FastAPI
    volumes:
      - chroma_data:/chroma/.chroma/index

volumes:
  postgres_data:
  chroma_data: