services:
  # A PostgreSQL database
  - type: psql # CORRECTED: Changed from 'pgsrv' to 'psql'
    name: workflow-db
    postgresMajorVersion: 15

  # The backend web service
  - type: web
    name: workflow-backend
    env: docker # Use the Dockerfile for building
    healthCheckPath: / # Render will check this path to see if your app is healthy
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: workflow-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false # Do not sync this secret to Git
      - key: SERPAPI_API_KEY
        sync: false # Do not sync this secret to Git
```

### What to Do Now

1.  **Replace the code** in your `render.yaml` file with the corrected version above.
2.  **Save the file.**
3.  **Commit and push** this change to your `main` branch on GitHub:
    ```bash
    git add render.yaml
    git commit -m "Fix render.yaml database service type"
    git push
    
